#!/bin/bash
# 脚本权限设置

chmod +x /root/webroot/SmartCam/scripts/*.sh
echo "✓ 脚本权限已设置"

cd /root/webroot/SmartCam

# 显示下一步说明
echo ""
echo "=========================================="
echo "SmartCam MVP 开发环境配置完成"
echo "=========================================="
echo ""
echo "📋 已创建的文件："
echo ""
echo "脚本文件:"
ls -lh scripts/*.sh 2>/dev/null | awk '{print "  " $9}' || echo "  未找到"
echo ""
echo "数据库:"
echo "  scripts/smartcam-db-init.sql"
echo ""
echo "配置文件:"
echo "  scripts/docker-compose.dev.yml"
echo "  ops/zlm/config.ini.dev"
echo ""
echo "=========================================="
echo ""
echo "🚀 快速开始（远程 Linux 服务器）："
echo ""
echo "第1步：以 root 身份运行服务器环境初始化"
echo "  sudo bash scripts/setup-dev-server.sh"
echo ""
echo "第2步：启动开发环境容器"
echo "  docker-compose -f scripts/docker-compose.dev.yml up -d"
echo ""
echo "第3步：初始化项目结构"
echo "  bash scripts/init-project.sh /opt/smartcam"
echo ""
echo "第4步：验证开发环境"
echo "  bash scripts/check-dev-env.sh"
echo ""
echo "第5步：启动开发"
echo "  后端: cd backend && go run ./cmd/server"
echo "  前端: cd frontend && npm install && npm run dev"
echo ""
echo "📖 更多详情见："
echo "  cat DEV_GUIDE.md"
echo ""
